In [6]:
import numpy as np
import pandas as pd
labels=['a','b','c']
my_data=[4,5,6]
a=np.array(my_data)
d={'a':4,'b':5,'c':6}

print(labels)
print(my_data)
print(d)

['a', 'b', 'c']
[4, 5, 6]
{'a': 4, 'b': 5, 'c': 6}

In [9]:
pd.Series(data=my_data)

0    4
1    5
2    6
dtype: int64

In [11]:
pd.Series(data=my_data,index=labels)

a    4
b    5
c    6
dtype: int64

In [13]:
import pandas as pd

ser1 = pd.Series([1, 2, 3, 4], ['CA', 'OR', 'CO', 'AZ'])
ser2 = pd.Series([1, 2, 5, 4], ['CA', 'OR', 'NV', 'AZ'])

print("\nIndexing by name of the item/object (string identifier)\n", "-" * 56, sep='')
print("Value for CA in ser1:", ser1['CA'])
print("Value for AZ in ser1:", ser1['AZ'])
print("Value for NV in ser2:", ser2['NV'])

print("\nIndexing by number (positional value in the series)\n", "-" * 52, sep='')
print("Value for CA in ser1:", ser1[0])
print("Value for AZ in ser1:", ser1[3])
print("Value for NV in ser2:", ser2[2])

print("\nIndexing by a range\n", "-" * 25, sep='')
print("Value for OR, CO, and AZ in ser1:\n", ser1[1:4], sep='')

Indexing by name of the item/object (string identifier)
--------------------------------------------------------
Value for CA in ser1: 1
Value for AZ in ser1: 4
Value for NV in ser2: 5

Indexing by number (positional value in the series)
----------------------------------------------------
Value for CA in ser1: 1
Value for AZ in ser1: 4
Value for NV in ser2: 5

Indexing by a range
-------------------------
Value for OR, CO, and AZ in ser1:
OR    2
CO    3
AZ    4
dtype: int64

C:\Windows\Temp\ipykernel_16940\3067264556.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print("Value for CA in ser1:", ser1[0])
C:\Windows\Temp\ipykernel_16940\3067264556.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print("Value for AZ in ser1:", ser1[3])
C:\Windows\Temp\ipykernel_16940\3067264556.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print("Value for NV in ser2:", ser2[2])

In [16]:
import pandas as pd

ser1 = pd.Series([1, 2, 3, 4], ['CA', 'OR', 'CO', 'AZ'])
ser2 = pd.Series([1, 2, 5, 4], ['CA', 'OR', 'NV', 'AZ'])
ser3=ser1+ser2
print(ser3)

AZ    8.0
CA    2.0
CO    NaN
NV    NaN
OR    4.0
dtype: float64

In [20]:
from numpy.random import random as rn

In [23]:
import numpy as np
import pandas as pd

np.random.seed(101)

matrix_data = np.random.randn(4, 5)

row_label = ['a', 'b', 'c', 'd']
column_label = ['w', 'x', 'y', 'z', 'v']

df = pd.DataFrame(data=matrix_data,
                  index=row_label,
                  columns=column_label)

print(df)

          w         x         y         z         v
a  2.706850  0.628133  0.907969  0.503826  0.651118
b -0.319318 -0.848077  0.605965 -2.018168  0.740122
c  0.528813 -0.589001  0.188695 -0.758872 -0.933237
d  0.955057  0.190794  1.978757  2.605967  0.683509

In [25]:
import numpy as np
import pandas as pd

np.random.seed(101)

matrix_data = np.random.randn(4, 5)

row_label = ['a', 'b', 'c', 'd']
column_label = ['w', 'x', 'y', 'z', 'v']

df = pd.DataFrame(matrix_data, index=row_label, columns=column_label)

print(df)

          w         x         y         z         v
a  2.706850  0.628133  0.907969  0.503826  0.651118
b -0.319318 -0.848077  0.605965 -2.018168  0.740122
c  0.528813 -0.589001  0.188695 -0.758872 -0.933237
d  0.955057  0.190794  1.978757  2.605967  0.683509

In [27]:
print(df.loc['a'])

w    2.706850
x    0.628133
y    0.907969
z    0.503826
v    0.651118
Name: a, dtype: float64

In [28]:
print(df.loc[['a', 'c']])

          w         x         y         z         v
a  2.706850  0.628133  0.907969  0.503826  0.651118
c  0.528813 -0.589001  0.188695 -0.758872 -0.933237

In [30]:
print(df.iloc[[0, 2]])

          w         x         y         z         v
a  2.706850  0.628133  0.907969  0.503826  0.651118
c  0.528813 -0.589001  0.188695 -0.758872 -0.933237

In [1]:
import pandas as pd
import numpy as np


df = pd.DataFrame({
    'A': [1, 2, np.nan],
    'B': [5, np.nan, np.nan],
    'C': [1, 2, 3]
})

df['States'] = 'CA NV AZ'.split()
df.set_index('States', inplace=True)

print(df)

          A    B  C
States
CA      1.0  5.0  1
NV      2.0  NaN  2
AZ      NaN  NaN  3

In [2]:
print("\nDropping any rows with a NaN value\n", "-" * 35, sep="")
print(df.dropna(axis=0))

print("\nDropping any column with a NaN value\n", "-" * 35, sep="")
print(df.dropna(axis=1))

print("\nDropping a row with a minimum 2 NaN values using 'thresh' parameter\n", "-" * 68, sep="")
print(df.dropna(axis=0, thresh=2))

Dropping any rows with a NaN value
-----------------------------------
          A    B  C
States
CA      1.0  5.0  1

Dropping any column with a NaN value
-----------------------------------
        C
States
CA      1
NV      2
AZ      3

Dropping a row with a minimum 2 NaN values using 'thresh' parameter
--------------------------------------------------------------------
          A    B  C
States
CA      1.0  5.0  1
NV      2.0  NaN  2

In [3]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'A': [1, 2, np.nan],
    'B': [5, np.nan, np.nan],
    'C': [1, 2, 3]
})

df['States'] = 'CA NV AZ'.split()
df.set_index('States', inplace=True)

print(df)
print(df.fillna(df.mean(numeric_only=True)))

          A    B  C
States
CA      1.0  5.0  1
NV      2.0  NaN  2
AZ      NaN  NaN  3
          A    B  C
States
CA      1.0  5.0  1
NV      2.0  5.0  2
AZ      1.5  5.0  3

In [5]:
import pandas as pd

data = {
    'Company': ['Google', 'Google', 'Microsoft', 'Microsoft', 'Facebook', 'Facebook'],
    'Person': ['Sam', 'Charlie', 'Amy', 'Vanessa', 'Carl', 'Sarah'],
    'Sales': [200, 120, 340, 124, 243, 350]
}

df = pd.DataFrame(data)

print(df)
print(byCompany['Sales'].agg(['sum', 'mean', 'max', 'min']))

     Company   Person  Sales
0     Google      Sam    200
1     Google  Charlie    120
2  Microsoft      Amy    340
3  Microsoft  Vanessa    124
4   Facebook     Carl    243
5   Facebook    Sarah    350
           sum   mean  max  min
Company
Facebook   593  296.5  350  243
Google     320  160.0  200  120
Microsoft  464  232.0  340  124

In [6]:
import pandas as pd

df1 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['Alice', 'Bob', 'Charlie']
})

df2 = pd.DataFrame({
    'ID': [1, 2, 4],
    'Department': ['HR', 'IT', 'Finance']
})

df3 = pd.DataFrame({
    'ID': [1, 3, 4],
    'Salary': [50000, 60000, 70000]
})

print("DataFrame 1")
print(df1)

print("\nDataFrame 2")
print(df2)

print("\nDataFrame 3")
print(df3)

DataFrame 1
   ID     Name
0   1    Alice
1   2      Bob
2   3  Charlie

DataFrame 2
   ID Department
0   1         HR
1   2         IT
2   4    Finance

DataFrame 3
   ID  Salary
0   1   50000
1   3   60000
2   4   70000

In [8]:
result1 = pd.concat([df1, df2, df3], axis=0)
print(result1)

   ID     Name Department   Salary
0   1    Alice        NaN      NaN
1   2      Bob        NaN      NaN
2   3  Charlie        NaN      NaN
0   1      NaN         HR      NaN
1   2      NaN         IT      NaN
2   4      NaN    Finance      NaN
0   1      NaN        NaN  50000.0
1   3      NaN        NaN  60000.0
2   4      NaN        NaN  70000.0

In [9]:
merge2 = pd.merge(df1, df2, on='ID')
merge3 = pd.merge(merge2, df3, on='ID')

print(merge3)

   ID   Name Department  Salary
0   1  Alice         HR   50000

In [10]:
df1_index = df1.set_index('ID')
df2_index = df2.set_index('ID')
df3_index = df3.set_index('ID')
join1 = df1_index.join(df2_index)
print(join1)

       Name Department
ID
1     Alice         HR
2       Bob         IT
3   Charlie        NaN

In [18]:
df1.head()

   ID     Name
0   1    Alice
1   2      Bob
2   3  Charlie

In [19]:

df2.tail()

   ID Department
0   1         HR
1   2         IT
2   4    Finance

In [21]:

import pandas as pd

df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Math': [85, 90, 78],
    'Science': [88, 76, 95]
})

print(df)

      Name  Math  Science
0    Alice    85       88
1      Bob    90       76
2  Charlie    78       95

In [22]:
def double(x):
    return x * 2

df['Math_Double'] = df['Math'].apply(double)

print(df)

      Name  Math  Science  Math_Double
0    Alice    85       88          170
1      Bob    90       76          180
2  Charlie    78       95          156